import { createErrorDomain } from '../utils';
import {
	AUDIT_LOG_ERROR_MESSAGES,
	AUTH_ERROR_MESSAGES,
	EMAIL_CONFIRMATION_ERROR_MESSAGES,
	INVITE_LINK_ERROR_MESSAGES,
	LINK_ERROR_MESSAGES,
	RESERVED_WORDS_ERROR_MESSAGES,
	ROLE_ERROR_MESSAGES,
	USER_ERROR_MESSAGES,
	USER_PROVIDER_ERROR_MESSAGES,
	WORKSPACE_ERROR_MESSAGES,
	WORKSPACE_MEMBER_ERROR_MESSAGES,
} from './error-messages';

export const ERRORS = {
	AUTH: createErrorDomain(AUTH_ERROR_MESSAGES),
	EMAIL_CONFIRMATION: createErrorDomain(EMAIL_CONFIRMATION_ERROR_MESSAGES),
	USER: createErrorDomain(USER_ERROR_MESSAGES),
	USER_PROVIDER: createErrorDomain(USER_PROVIDER_ERROR_MESSAGES),
	LINK: createErrorDomain(LINK_ERROR_MESSAGES),
	RESERVED_WORDS: createErrorDomain(RESERVED_WORDS_ERROR_MESSAGES),
	WORKSPACE: createErrorDomain(WORKSPACE_ERROR_MESSAGES),
	WORKSPACE_MEMBER: createErrorDomain(WORKSPACE_MEMBER_ERROR_MESSAGES),
	ROLE: createErrorDomain(ROLE_ERROR_MESSAGES),
	AUDIT_LOG: createErrorDomain(AUDIT_LOG_ERROR_MESSAGES),
	INVITE_LINK: createErrorDomain(INVITE_LINK_ERROR_MESSAGES),
} as const;
